_Q_STRINGS_EYEFISERVER = {
	_APP_TITLE: "Eye-Fi Server",
	_MAIN_MENU_ITEM_CARDS: "Cards",
	_MAIN_MENU_ITEM_UPLOAD: "Upload",
	_MAIN_MENU_ITEM_GEOTAGGING: "Geotagging",
	_MAIN_MENU_ITEM_LOG: "Log",
	_LABEL_CARD_1: "Eye-Fi Card 1",
	_LABEL_CARD_1_HELP: "You can find these values after configuring the card. It is inside %AppData%\\Eye-Fi\\Settings.xml on Windows or ~/Applications Data/Eye-Fi/Settings.xml on Mac search for it and paste it here.",
	_LABEL_CARD_2: "Eye-Fi Card 2",
	_LABEL_CARD_2_HELP: "Additional Eye-Fi card configuration, same as above.",
	_LABEL_MAC_ADDRESS: "MAC address",
	_LABEL_UPLOAD_KEY: "Upload key",
	_LABEL_UPLOAD_DIR: "Path",
	_LABEL_UPLOAD_DIR_HELP: "The name of the directory can be a strftime formatted string like /share/Multimedia/Eye-Fi/%%Y-%%m-%%d.",
	_LABEL_UPLOAD_PERMISSIONS: "Permissions",
	_LABEL_UPLOAD_FILES: "Files",
	_LABEL_UPLOAD_DIRECTORIES: "Directories",
	_LABEL_UPLOAD_READ: "read",
	_LABEL_UPLOAD_WRITE: "write",
	_LABEL_UPLOAD_EXECUTE: "execute",
	_LABEL_UPLOAD_OTHERS: "others",
	_LABEL_GEOTAG_ENABLE: "Enable geotagging",
	_LABEL_GEOTAG_ENABLE_HELP: "Create XMP file with geolocation information based on access points detected by Eye-Fi card for any uploaded JPEG or RAW file.",
	_LABEL_GEOTAG_LAG: "Time lag",
	_LABEL_GEOTAG_LAG_HELP: "Use access points detected within this period of time before or after photo was taken, in seconds.",
	_LABEL_GEOTAG_ACCURACY: "Distance",
	_LABEL_GEOTAG_ACCURACY_HELP: "Use acquired geolocation data with accuracy below this value, in meters. Too big values such as default 140000 will result of adding a geolocation data of a server even if there was no suitable access points for a photo.",
	_LABEL_STATUS: "Status",
	_LABEL_LOG: "Log",
	_OK_BUTTON_TEXT: "OK",
	_APPLY_BUTTON_TEXT: "Apply",
	_REVERT_BUTTON_TEXT: "Revert",
	_STOP_BUTTON_TEXT: "Stop",
	_START_BUTTON_TEXT: "Start",
	_RESTART_BUTTON_TEXT: "Restart",
	_CLEAR_LOG_BUTTON_TEXT: "Clear log",
	_REFRESH_BUTTON_TEXT: "Refresh",
	_NORTH_REGION_INFO_BUTTON_TOOLTIP: "About",
	_INFO_WINDOW_APP_NAME: "APP Name",
	_INFO_WINDOW_COPYRIGHT: "https://github.com/dgrant/eyefiserver2",
	_INFO_WINDOW_APP_VERSION: "APP Version"
};
