_Q_STRINGS_EYEFISERVER = {
	_APP_TITLE: "Eye-Fi Server",
	_MAIN_MENU_ITEM_CARDS: "Карты",
	_MAIN_MENU_ITEM_UPLOAD: "Загрузка",
	_MAIN_MENU_ITEM_GEOTAGGING: "Геотегинг",
	_MAIN_MENU_ITEM_LOG: "Журнал",
	_LABEL_CARD_1: "Eye-Fi карта 1",
	_LABEL_CARD_1_HELP: "Вы можете получить эти значения после выполнения настройки карты. Найдите их в файле %AppData%\\Eye-Fi\\Settings.xml в Windows или ~/Applications Data/Eye-Fi/Settings.xml в Mac OS и перенесите значения в эти поля.",
	_LABEL_CARD_2: "Eye-Fi карта 2",
	_LABEL_CARD_2_HELP: "Настройки дополнительной карты Eye-Fi, аналогичные первой.",
	_LABEL_MAC_ADDRESS: "MAC адрес",
	_LABEL_UPLOAD_KEY: "Ключ загрузки",
	_LABEL_UPLOAD_DIR: "Путь",
	_LABEL_UPLOAD_DIR_HELP: "Допускается использовать строку в формате strftime, например /share/Multimedia/Eye-Fi/%%Y-%%m-%%d.",
	_LABEL_UPLOAD_PERMISSIONS: "Права",
	_LABEL_UPLOAD_FILES: "Файлы",
	_LABEL_UPLOAD_DIRECTORIES: "Каталоги",
	_LABEL_UPLOAD_READ: "чтение",
	_LABEL_UPLOAD_WRITE: "запись",
	_LABEL_UPLOAD_EXECUTE: "выполнение",
	_LABEL_UPLOAD_OTHERS: "другие",
	_LABEL_GEOTAG_ENABLE: "Включить геотегинг",
	_LABEL_GEOTAG_ENABLE_HELP: "Создавать файл XMP с информацией о геолокации на основе обнаруженных Eye-Fi картой точек доступа для всех загружаемых файлов JPEG и RAW.",
	_LABEL_GEOTAG_LAG: "Задержка",
	_LABEL_GEOTAG_LAG_HELP: "Использовать информацию о точках доступа, обнаруженных за промежуток времени до или после снятия кадра, в секундах.",
	_LABEL_GEOTAG_ACCURACY: "Расстояние",
	_LABEL_GEOTAG_ACCURACY_HELP: "Использовать полученную геолокацию с точностью не более заданного значения в метрах. Слишком большое значение, в т.ч. заданное по умолчанию 140000, приведет к добавлению геолокации сервера, даже если не было найдено подходящих точек доступа для кадра.",
	_LABEL_STATUS: "Состояние",
	_LABEL_LOG: "Журнал",
	_OK_BUTTON_TEXT: "OK",
	_APPLY_BUTTON_TEXT: "Применить",
	_REVERT_BUTTON_TEXT: "Восстановить",
	_STOP_BUTTON_TEXT: "Остановить",
	_START_BUTTON_TEXT: "Запустить",
	_RESTART_BUTTON_TEXT: "Перезапустить",
	_CLEAR_LOG_BUTTON_TEXT: "Очистить журнал",
	_REFRESH_BUTTON_TEXT: "Обновить",
	_NORTH_REGION_INFO_BUTTON_TOOLTIP: "О программе",
	_INFO_WINDOW_APP_NAME: "Имя приложения",
	_INFO_WINDOW_COPYRIGHT: "https://github.com/dgrant/eyefiserver2",
	_INFO_WINDOW_APP_VERSION: "Версия приложения"
};
