#!/bin/sh
NAME=eyefiserver
CONF=/etc/config/qpkg.conf
CFGFILE=/etc/$NAME.conf
LOGFILE=/var/log/$NAME.log
DAEMON=/usr/local/bin/$NAME.py
if [ -f $CONF ]; then
	QPKG_NAME="EyeFiServer"
	QPKG_DIR=$(/sbin/getcfg $QPKG_NAME Install_Path -d "" -f $CONF)
	ENABLED=$(/sbin/getcfg $QPKG_NAME Enable -u -d FALSE -f $CONF)
	[ -a $DAEMON ] || ln -s $QPKG_DIR/$NAME.py $DAEMON
	[ -a $CFGFILE ] || ln -s /etc/config/$NAME.conf $CFGFILE
else
	ENABLED="TRUE"
fi
case "$1" in
start)
	[ "$ENABLED" == "FALSE" ] && echo "$QPKG_NAME is disabled." && exit 1
	$DAEMON start $CFGFILE $LOGFILE
	;;
stop|restart|reload|instance)
	$DAEMON $1 $CFGFILE $LOGFILE
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload|instance}"
	exit 1
esac
exit 0
